// Code generated by MockGen. DO NOT EDIT.
// Source: calculation_updater.go
//
// Generated by this command:
//
//	mockgen -source calculation_updater.go -destination calculation_updater_mock.go -package calculation
//

// Package calculation is a generated GoMock package.
package calculation

import (
	reflect "reflect"

	domain "github.com/hawkv6/hawkeye/pkg/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCalculationUpdater is a mock of CalculationUpdater interface.
type MockCalculationUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockCalculationUpdaterMockRecorder
}

// MockCalculationUpdaterMockRecorder is the mock recorder for MockCalculationUpdater.
type MockCalculationUpdaterMockRecorder struct {
	mock *MockCalculationUpdater
}

// NewMockCalculationUpdater creates a new mock instance.
func NewMockCalculationUpdater(ctrl *gomock.Controller) *MockCalculationUpdater {
	mock := &MockCalculationUpdater{ctrl: ctrl}
	mock.recorder = &MockCalculationUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculationUpdater) EXPECT() *MockCalculationUpdaterMockRecorder {
	return m.recorder
}

// UpdateCalculation mocks base method.
func (m *MockCalculationUpdater) UpdateCalculation(arg0 *CalculationUpdateOptions) (domain.PathResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCalculation", arg0)
	ret0, _ := ret[0].(domain.PathResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCalculation indicates an expected call of UpdateCalculation.
func (mr *MockCalculationUpdaterMockRecorder) UpdateCalculation(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCalculation", reflect.TypeOf((*MockCalculationUpdater)(nil).UpdateCalculation), arg0)
}
